language: csharp
mono: none
dotnet: 3.1.201

before_install:
  cd ./src

install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test --collect:"XPlat Code Coverage"

  after_script:
        - bash <(curl -s https://codecov.io/bash)
